### ISSUE TITLE
replace usearch with vsearch

### ISSUE THREAD

**Issue by colinbrislawn** [brwnj/hundo#6]
[vsearch](https://github.com/torognes/vsearch) is an open source implementation of USEARCH, which we could use as part of this pipeline.

The following USEARCH commands appear in some rules of the Snakefile:

```
usearch -makeudb_utax
usearch -makeudb_usearch
usearch -fastq_mergepairs
usearch -fastq_filter
usearch -fastx_uniques
usearch -cluster_otus
usearch -uchime2_ref
usearch -utax
usearch -usearch_global
```

VSEARCH currently implements these 3 commands, and should serve as a drop in replacement.

```
vsearch --fastq_mergepairs
vsearch --fastq_filter
vsearch --usearch_global
```

While only 3 of these are implemented in vsearch, similar functionality could be recreated for all of them. Also, vsearch is under active development, so additional feature may be forthcoming.

**Comment by brwnj** [comment]
Fixed in 8f0d164bd2b1ed8745f9a2ef44eee70da7d7db21.
